version: '3'
services:
  jupyter:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
     - "8888:8888"
    volumes: 
     - ./:/home/jovyan/ 
  db:
    image: postgres
    restart: always
    volumes:
    - ./database:/var/lib/postgresql/data
    ports:
     - "5432:5432"
volumes: 
  pgdata: